behaviors:
  RedCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096         # Aumentato per sfruttare meglio la potenza
      buffer_size: 40960       # 10x batch_size
      learning_rate: 3.0e-4    
      beta: 5.0e-3            
      epsilon: 0.2            
      lambd: 0.95
      num_epoch: 4            # Aumentato per migliore utilizzo dei dati
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512       # Rete più grande per maggiore capacità
      num_layers: 3           # Layer aggiuntivo per complessità
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99           
        strength: 1.0
      curiosity:              
        gamma: 0.99
        strength: 0.05        
        encoding_size: 256    # Encoding più grande
        learning_rate: 1.0e-3
    keep_checkpoints: 5
    max_steps: 3.0e6          # Ridotto per 1h di training
    time_horizon: 1000        
    summary_freq: 10000       # Più frequente per monitoring
    checkpoint_interval: 50000 # Più frequente per sicurezza
    
  BlueCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048         # Aumentato
      buffer_size: 20480
      learning_rate: 5.0e-4    
      beta: 1.0e-2            
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4            # Aumentato
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256       # Aumentato
      num_layers: 3           # Layer aggiuntivo
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:              # Aggiunta curiosity anche per BlueCar
        gamma: 0.99
        strength: 0.03        # Più leggera del RedCar
        encoding_size: 128
        learning_rate: 1.0e-3
    keep_checkpoints: 5
    max_steps: 3.0e6          # Stesso target del RedCar
    time_horizon: 1000        # Allineato con RedCar
    summary_freq: 10000
    checkpoint_interval: 50000

# Configurazioni per prestazioni massime
engine_settings:
  width: 84
  height: 84
  quality_level: 0          # Qualità minima per velocità massima
  time_scale: 10            # Accelerazione molto alta per 1h training
  target_frame_rate: 120    # Frame rate alto se supportato
  # Configurazioni aggiuntive per prestazioni
  no_graphics: false        # Mantieni grafica per debugging, cambia in true se vuoi velocità pura