behaviors:
  RedCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096        # Aumentato per sfruttare la GPU potente
      buffer_size: 40960      # Raddoppiato rispetto al batch_size * 10
      learning_rate: 5.0e-4   # Leggermente aumentato per convergenza più veloce
      beta: 1.0e-3           # Ridotto per stabilità con batch più grandi
      epsilon: 0.15          # Leggermente ridotto per maggiore stabilità
      lambd: 0.95
      num_epoch: 4           # Aumentato per sfruttare meglio i batch grandi
      learning_rate_schedule: linear  # Migliore per training lunghi
    network_settings:
      normalize: true
      hidden_units: 512      # Aumentato per sfruttare la GPU potente
      num_layers: 3          # Aggiunto un layer per maggiore capacità
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995         # Leggermente aumentato per planning a lungo termine
        strength: 1.0
      curiosity:             # Aggiunta curiosity per esplorazioni migliori
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 1.0e-3
    keep_checkpoints: 10     # Più checkpoints per sicurezza
    max_steps: 8.0e6         # Aumentato per almeno 1h+ di training
    time_horizon: 2000       # Raddoppiato per episodi più lunghi
    summary_freq: 25000      # Meno frequente per ridurre I/O
    checkpoint_interval: 200000  # Checkpoint ogni 200k steps
    
  BlueCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 5.0e-4
      beta: 1.0e-3
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 1.0e-3
    keep_checkpoints: 10
    max_steps: 8.0e6
    time_horizon: 2000
    summary_freq: 25000
    checkpoint_interval: 200000

# Configurazioni globali opzionali per prestazioni
engine_settings:
  width: 84                  # Risoluzione ridotta per velocità se usi osservazioni visive
  height: 84
  quality_level: 1           # Qualità grafica ridotta per prestazioni
  time_scale: 20             # Accelera la simulazione (regola in base alle tue esigenze)
  target_frame_rate: -1      # Nessun limite FPS